services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:${DB_PORT}"

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: True
      API_KEY: ${API_KEY}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/app